version: 2
jobs:
  build:
    branches:
      only:
        - assignment5
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build Artifact
          command: |
            pwd
            ./mvnw clean install 
      
