version: 2
jobs:
  build:
    branches:
      only:
        - assignment5
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build Artifact
          command: |
            pwd
            mvn clean install 
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            ls -al
      - run:
          name: Upload Artifact to S3
          command: |
            echo "Hello"
      - run:
          name: Make CodeDeploy API call
          command: |
            echo "Hello CodeDeploy" 
